eva_bimanual:
  _target_: egomimic.rldb.embodiment.eva.Eva.viz_gt_preds
  _partial_: true
  image_key: observations.images.front_img_1
  action_key: actions_cartesian
  annotation_key: sampled_prompt
  mode: traj
aria_bimanual:
  _target_: egomimic.rldb.embodiment.human.Aria.viz_gt_preds
  _partial_: true
  image_key: observations.images.front_img_1
  action_key: actions_cartesian
  annotation_key: sampled_prompt
  mode: traj
mecka_bimanual:
  _target_: egomimic.rldb.embodiment.human.Mecka.viz_gt_preds
  _partial_: true
  image_key: observations.images.front_img_1
  action_key: actions_cartesian
  annotation_key: sampled_prompt
  mode: traj
scale_bimanual:
  _target_: egomimic.rldb.embodiment.human.Scale.viz_gt_preds
  _partial_: true
  image_key: observations.images.front_img_1
  action_key: actions_cartesian
  annotation_key: sampled_prompt
  mode: traj
