defaults:
  - model: hpt_bc_flow_eva
  - paths: default
  - trainer: ddp
  - debug: null
  - logger: wandb
  - data: eva
  - callbacks: checkpoints
  - data_schematic: default
  - evaluator: eval_hpt
  - override hydra/launcher: submitit
  - _self_

name: test
description: test
ckpt_path: null
mode: train

hydra:
  run:
    # Dir should be experiment_name/description_{timestamp}
    dir: ./logs/${name}/${description}_${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ./logs/${name}/${description}_${now:%Y-%m-%d_%H-%M-%S}

launch_params:
  gpus_per_node: 1
  nodes: 1

seed: 42

# Normalization and norm-stat cache settings (override per-run as needed).
norm_stats:
  sample_frac: 1.0
  num_workers: 4
  save_cache_dir: ${hydra:runtime.output_dir}
  precomputed_norm_path: null
reject_outliers: true
