defaults:
  - train_zarr_cartesian
  - override model: hpt_bc_flow_static_camera_franka30
  - override data: static_camera_franka30
  - _self_

name: static_camera_franka30
description: hpt_flow_next_observation_30hz_45_front_wrist

norm_stats:
  norm_mode: quantile
  sample_frac: 1.0

evaluator:
  viz_func: null
