# path to root directory
root_dir: ${hydra:runtime.cwd}

# # path to data directory
# data_dir: ${paths.root_dir}/data/

# default folder containing zarr episode datasets
dataset_dir: /coc/flash7/scratch/egoverseS3ZarrDataset

# local folders containing custom converted Zarr episode datasets
custom_human_dataset_dir: ./data/custom_human_azure_kinect_zarr
custom_franka_dataset_dir: ./data/custom_franka_zarr

# MimicGen paired pick-place dataset directories
mimicgen_franka_dataset_dir: /home/ubuntu/data/mimicgen_pickplace_franka_zarr
mimicgen_sawyer_dataset_dir: /home/ubuntu/data/mimicgen_pickplace_sawyer_zarr

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
